- hosts: servidores
  become: true
  tasks:
    - name: "Comprobamos si tiene conectividad"
      ansible.builtin.ping:
    - name: "Actualizamos el sistema"
      apt: update=yes
    - name: "Instalar paquete"
    